### ISSUE TITLE
(Input Bug) Should ask again if file name is wrong

### ISSUE THREAD

**Issue by abiddouglas** [CMPT-2276-001-Douglas-College/hw1-Phuong-Matthew-Abidali#56]
The program stops if the file name is entered wrong. Users should get a chance to enter the file name/path again or end the program.

![Image](https://user-images.githubusercontent.com/110199013/218091939-84ec8e69-ac3b-4cd4-8995-54ed3f55c4f0.png)

**Comment by LostCauseSauce** [comment]
Not a bug. This can be done in later release than 1.0.0.
